### ISSUE TITLE
[Connection refused] using precompiled server

### ISSUE THREAD

**Issue by mmatyas** [glymehrvrd/CppYCM#17]
On Ubuntu 14.04 x64, using [your precompiled YCMD](https://github.com/glymehrvrd/CppYCM/tree/compiled-ycmd), the following error happens after starting ST3:

```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 333, in on_activated_async
    callback.on_activated_async(v)
  File "listeners.loadextraconf in /home/mmatyas/.config/sublime-text-3/Installed Packages/C++YouCompleteMe.sublime-package", line 40, in on_activated_async
  File "lib.ycmd_handler in /home/mmatyas/.config/sublime-text-3/Installed Packages/C++YouCompleteMe.sublime-package", line 31, in server
  File "lib.ycmd_handler in /home/mmatyas/.config/sublime-text-3/Installed Packages/C++YouCompleteMe.sublime-package", line 179, in WaitUntilReady
RuntimeError: waited for the server for 5 seconds, aborting
```

Then the console is filled with errors like this:

```
[C++YouCompleteMe] Start completing.
Exception in thread CompleteAsync:
Traceback (most recent call last):
  File "./urllib/request.py", line 1248, in do_open
  File "./http/client.py", line 1065, in request
  File "./http/client.py", line 1103, in _send_request
  File "./http/client.py", line 1061, in endheaders
  File "./http/client.py", line 906, in _send_output
  File "./http/client.py", line 844, in send
  File "./http/client.py", line 822, in connect
  File "./socket.py", line 435, in create_connection
  File "./socket.py", line 426, in create_connection
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "./threading.py", line 858, in run
  File "listeners.autocomplete in /home/mmatyas/.config/sublime-text-3/Installed Packages/C++YouCompleteMe.sublime-package", line 47, in complete_func
  File "lib.ycmd_handler in /home/mmatyas/.config/sublime-text-3/Installed Packages/C++YouCompleteMe.sublime-package", line 131, in SendCodeCompletionRequest
  File "lib.ycmd_handler in /home/mmatyas/.config/sublime-text-3/Installed Packages/C++YouCompleteMe.sublime-package", line 107, in PostToHandler
  File "lib.ycmd_handler in /home/mmatyas/.config/sublime-text-3/Installed Packages/C++YouCompleteMe.sublime-package", line 205, in _CallHttp
  File "./urllib/request.py", line 156, in urlopen
  File "./urllib/request.py", line 469, in open
  File "./urllib/request.py", line 487, in _open
  File "./urllib/request.py", line 447, in _call_chain
  File "./urllib/request.py", line 1268, in http_open
  File "./urllib/request.py", line 1251, in do_open
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>
```

**Comment by Urich** [comment]
ST3 Build 3114
uname -a 
Linux usc 4.0.5-gentoo #1 SMP Mon Oct 5 11:51:56 MSK 2015 x86_64 AMD Phenom(tm) II X6 1055T Processor AuthenticAMD GNU/Linux
I m build from master. Commit date: Sun Jun 19 08:35

```
Traceback (most recent call last):
  File "/opt/sublime_text_3/sublime_plugin.py", line 333, in on_activated_async
    callback.on_activated_async(v)
  File "listeners.loadextraconf in /home/urich/.config/sublime-text-3/Installed Packages/C++YouCompleteMe.sublime-package", line 40, in on_activated_async
  File "lib.ycmd_handler in /home/urich/.config/sublime-text-3/Installed Packages/C++YouCompleteMe.sublime-package", line 31, in server
  File "lib.ycmd_handler in /home/urich/.config/sublime-text-3/Installed Packages/C++YouCompleteMe.sublime-package", line 179, in WaitUntilReady
RuntimeError: waited for the server for 5 seconds, aborting
[C++YouCompleteMe] Start completing.
Exception in thread CompleteAsync:
Traceback (most recent call last):
  File "./python3.3/urllib/request.py", line 1248, in do_open
  File "./python3.3/http/client.py", line 1065, in request
  File "./python3.3/http/client.py", line 1103, in _send_request
  File "./python3.3/http/client.py", line 1061, in endheaders
  File "./python3.3/http/client.py", line 906, in _send_output
  File "./python3.3/http/client.py", line 844, in send
  File "./python3.3/http/client.py", line 822, in connect
  File "./python3.3/socket.py", line 435, in create_connection
  File "./python3.3/socket.py", line 426, in create_connection
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "listeners.autocomplete in /home/urich/.config/sublime-text-3/Installed Packages/C++YouCompleteMe.sublime-package", line 47, in complete_func
  File "lib.ycmd_handler in /home/urich/.config/sublime-text-3/Installed Packages/C++YouCompleteMe.sublime-package", line 131, in SendCodeCompletionRequest
  File "lib.ycmd_handler in /home/urich/.config/sublime-text-3/Installed Packages/C++YouCompleteMe.sublime-package", line 107, in PostToHandler
  File "lib.ycmd_handler in /home/urich/.config/sublime-text-3/Installed Packages/C++YouCompleteMe.sublime-package", line 205, in _CallHttp
  File "./python3.3/urllib/request.py", line 156, in urlopen
  File "./python3.3/urllib/request.py", line 469, in open
  File "./python3.3/urllib/request.py", line 487, in _open
  File "./python3.3/urllib/request.py", line 447, in _call_chain
  File "./python3.3/urllib/request.py", line 1274, in http_open
  File "./python3.3/urllib/request.py", line 1251, in do_open
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>
```
