### ISSUE TITLE
[Errno 13] Permission denied

### ISSUE THREAD

**Issue by hamzamerzic** [glymehrvrd/CppYCM#5]
I get the fallowing error:
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 311, in on_activated_async
    callback.on_activated_async(v)
  File "listeners.loadextraconf in /home/hamza/.config/sublime-text-3/Installed Packages/C++YouCompleteMe.sublime-package", line 40, in on_activated_async
  File "lib.ycmd_handler in /home/hamza/.config/sublime-text-3/Installed Packages/C++YouCompleteMe.sublime-package", line 30, in server
  File "lib.ycmd_handler in /home/hamza/.config/sublime-text-3/Installed Packages/C++YouCompleteMe.sublime-package", line 87, in StartYcmdAndReturnHandle
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1448, in _execute_child
PermissionError: [Errno 13] Permission denied

After that I keep getting the fallowing messages:
[C++YouCompleteMe] Start completing.
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 358, in on_query_completions
    res = callback.on_query_completions(v, prefix, locations)
  File "listeners.autocomplete in /home/hamza/.config/sublime-text-3/Installed Packages/C++YouCompleteMe.sublime-package", line 79, in on_query_completions
  File "lib.ycmd_handler in /home/hamza/.config/sublime-text-3/Installed Packages/C++YouCompleteMe.sublime-package", line 35, in server
RuntimeError: [C++YouCompleteMe] Ycmd server is not loaded.

Any help would be appreciated. Thank you.

**Comment by glymehrvrd** [comment]
It seems the system could not start ycmd, have you set `python_path` and `ycmd_path` correctly?

**Comment by hamzamerzic** [comment]
Thank you for the answer. I'm sure that the ycmd path is set correctly, as it contains the listed necessary files, and it doesn't give me a "Ycmd not found error" at startup. I'm not quite sure about the python path; I put the default path on Ubuntu: "python_path": "/usr/lib/python2.7", or
maybe it has something to do with accessing files without permission, but I cannot read which files are those.

**Comment by glymehrvrd** [comment]
Try `cd YOUR_YCMD_PATH` and `python ycmd`, see if the ycmd server starts correctly.
There should be an output like `serving on http://127.0.0.1:xxxxx`

**Comment by hamzamerzic** [comment]
Hi. I did everything from above, and get the output from ycmd, but autocomplete still does not work. I will try to tinker a bit more in the error panel, and if I get something I will post it here.

**Comment by hamzamerzic** [comment]
Sorry for not getting back sooner. I tried to solve it, but had no success. It is actually a permission problem with subprocess.py. There were similar errors reported (i.e. here http://stackoverflow.com/questions/18940862/oserror-errno-13-permission-denied-python-subprocess-call), but nothing which could help me fix the issue.
Anyway, as this is probably not the issue with CppYCM, I am closing this thread.
