### ISSUE TITLE
Unauthorized Request

### ISSUE THREAD

**Issue by Jmeyer1292** [glymehrvrd/CppYCM#9]
Hi. I installed the package through the package manager but whenever I go to complete something I get the following error in the terminal:

```
File "/home/jon/.config/sublime-text-3/Packages/CppYCM/lib/ycmd_handler.py", line 200, in _CallHttp
    resp = urlopen(req)
  File "./urllib/request.py", line 156, in urlopen
  File "./urllib/request.py", line 475, in open
  File "./urllib/request.py", line 587, in http_response
  File "./urllib/request.py", line 513, in error
  File "./urllib/request.py", line 447, in _call_chain
  File "./urllib/request.py", line 595, in http_error_default
urllib.error.HTTPError: HTTP Error 401: Unauthorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./json/decoder.py", line 368, in raw_decode
  File "./json/scanner.py", line 63, in _scan_once
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 312, in on_activated_async
    callback.on_activated_async(v)
  File "/home/jon/.config/sublime-text-3/Packages/CppYCM/listeners/loadextraconf.py", line 40, in on_activated_async
    server(view.file_name())
  File "/home/jon/.config/sublime-text-3/Packages/CppYCM/lib/ycmd_handler.py", line 31, in server
    _server.WaitUntilReady()
  File "/home/jon/.config/sublime-text-3/Packages/CppYCM/lib/ycmd_handler.py", line 181, in WaitUntilReady
    if self.IsReady(include_subservers):
  File "/home/jon/.config/sublime-text-3/Packages/CppYCM/lib/ycmd_handler.py", line 99, in IsReady
    resp = self.GetFromHandler('ready', params)
  File "/home/jon/.config/sublime-text-3/Packages/CppYCM/lib/ycmd_handler.py", line 114, in GetFromHandler
    return self._CallHttp('get', handler)
  File "/home/jon/.config/sublime-text-3/Packages/CppYCM/lib/ycmd_handler.py", line 204, in _CallHttp
    json.loads(readData).get('message', '')))
  File "./json/__init__.py", line 319, in loads
  File "./json/decoder.py", line 352, in decode
  File "./json/decoder.py", line 370, in raw_decode
ValueError: No JSON object could be decoded
```

Any help or advice would be appreciated.

**Comment by glymehrvrd** [comment]
Unauthorized? The YCMD server must have some problems. Try my precompiled YCMD server if you use Ubuntu x64, or you might recompile your YCMD server and try again.

**Comment by Jmeyer1292** [comment]
Hey! Thanks for responding, and thank you for working on this awesome plugin!

The issue appears to be a change to how the HMAC is calculated. See more details here:
https://github.com/Valloric/ycmd/issues/113

I started looking into fixing it, but I got a bit bogged down I'll admit.

**Comment by glymehrvrd** [comment]
Ok, I will update this plugin to fit the lastest YCMD server, thanks for your reminding.

**Comment by zonyitoo** [comment]
Has this problem solved? I still got this error while running the plugin under Windows.

**Comment by welkineins** [comment]
@zonyitoo If you use prebuild YCMD server in instruction. The binary is not include the HMAC change yet, so you need to checkout CppYCM back to commit 6a67e9edb08636f7a75679ea2ed62eb61f3d9c84 to use old algorithm.

Hi @glymehrvrd, I suggest create an branch for windows or adding notes on readme.
Thank you.

**Comment by jimbo1qaz** [comment]
Now the opposite problem:

https://github.com/glymehrvrd/CppYCM#set-up-ycmd

The Windows installation guide provides a downloadable ycmd.zip. Although created in 2015, it bundles a 2014 version. As a result, I get the same HMAC mismatch error.

I'll upload a build at some point.
